/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface TechnicianSkillDto {
    idSkill?: number;
    idProfile?: number;
    idCategory?: number;
    nameSkill?: string;
    description?: string;
    level?: number;
}

export interface TechnicianProfileUpdateDto {
    bio?: string;
    idCategory?: number;
    yearsExperience?: number;
    hourlyRate?: number;
}

export interface TechnicianProfileResponseDto {
    id?: number;
    technicianId?: number;
    bio?: string;
    idCategory?: number;
    yearsExperience?: number;
    hourlyRate?: number;
    availabilityStatus?: 'AVAILABLE' | 'BUSY' | 'UNAVAILABLE' | 'ON_BREAK';
    verified?: boolean;
    completedJobs?: number;
    averageRating?: number;
}

export interface Rating {
    value?: number;
    poor?: boolean;
    label?: string;
    excellent?: boolean;
}

export interface ReviewDto {
    idReview?: number;
    idClient?: number;
    rating?: Rating;
    comment?: string;
    createdAt?: Date;
}

export interface ReservationDto {
    idReservation?: number;
    idClient?: number;
    idTechnician?: number;
    idReview?: number;
    dateRequested?: Date;
    scheduledTime?: Date;
    status?: 'PENDING' | 'ACCEPTED' | 'EN_ROUTE' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED' | 'REJECTED';
    price?: number;
    address?: string;
    description?: string;
    cancellationReason?: string;
    createdAt?: Date;
    updatedAt?: Date;
    completedAt?: Date;
}

export interface FactureDto {
    idFacture?: number;
    idReservation?: number;
    pdfUrl?: string;
    amount?: number;
    generatedAt?: Date;
    invoiceNumber?: string;
}

export interface CategoryDto {
    idCategory?: number;
    name?: string;
    description?: string;
    iconUrl?: string;
    active?: boolean;
    displayOrder?: number;
}

export interface Technician {
    idUser?: number;
    firstName?: string;
    lastName?: string;
    email?: string;
    phone?: string;
    password?: string;
    role?: 'CLIENT' | 'TECHNICIAN' | 'ADMIN';
    city?: string;
    neighborhood?: string;
    createdAt?: Date;
    updatedAt?: Date;
    active?: boolean;
    emailVerified?: boolean;
    phoneVerified?: boolean;
    profilePhotoUrl?: string;
    fullName?: string;
    client?: boolean;
    technician?: boolean;
    admin?: boolean;
}

export interface TechnicianProfileCreateDto {
    bio?: string;
    idCategory?: number;
    yearsExperience?: number;
    hourlyRate?: number;
}

export interface RegisterDto {
    firstName?: string;
    lastName?: string;
    email?: string;
    password?: string;
    phone?: string;
    city?: string;
    neighborhood?: string;
    profilePhotoUrl?: string;
}

export interface RegisterResponseDto {
    token?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    phone?: string;
    city?: string;
    neighborhood?: string;
    profilePhotoUrl?: string;
}

export interface AuthRequest {
    email?: string;
    password?: string;
}

export interface AuthResponse {
    token?: string;
    userId?: number;
    firsName?: string;
    lastName?: string;
    active?: boolean;
}

export interface RegisterAdminDto {
    firstName?: string;
    lastName?: string;
    email?: string;
    password?: string;
    phone?: string;
    city?: string;
    neighborhood?: string;
    profilePhotoUrl?: string;
}

export interface ClientDto {
    firstName?: string;
    lastName?: string;
    email?: string;
    password?: string;
    phone?: string;
    city?: string;
    neighborhood?: string;
    profilePhotoUrl?: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
