/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface TechnicianSkillDto {
    idSkill?: number;
    idUser?: number;
    idCategory?: number;
    name?: string;
    description?: string;
    level?: number;
    yearsExperience?: number;
    hourlyRate?: number;
    availabilityStatus?: 'AVAILABLE' | 'BUSY' | 'UNAVAILABLE' | 'ON_BREAK';
    verified?: boolean;
    createdAt?: Date;
    updatedAt?: Date;
}

export interface Rating {
    value?: number;
    label?: string;
    poor?: boolean;
    excellent?: boolean;
}

export interface ReviewDto {
    idReview?: number;
    idClient?: number;
    idReservation?: number;
    rating?: Rating;
    comment?: string;
    createdAt?: Date;
}

export interface ReservationDto {
    idReservation?: number;
    idClient?: number;
    idTechnician?: number;
    idReview?: number;
    dateRequested?: Date;
    scheduledTime?: Date;
    status?: 'PENDING' | 'ACCEPTED' | 'EN_ROUTE' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED' | 'REJECTED';
    price?: number;
    city?: string;
    neighborhood?: string;
    description?: string;
    cancellationReason?: string;
    createdAt?: Date;
    updatedAt?: Date;
    completedAt?: Date;
}

export interface FactureDto {
    idFacture?: number;
    idReservation?: number;
    pdfUrl?: string;
    amount?: number;
    generatedAt?: Date;
    invoiceNumber?: string;
}

export interface CategoryDto {
    idCategory?: number;
    name?: string;
    description?: string;
    iconUrl?: string;
    active?: boolean;
    displayOrder?: number;
}

export interface Technician {
    idUser?: number;
    firstName?: string;
    lastName?: string;
    email?: string;
    phone?: string;
    password?: string;
    role?: 'CLIENT' | 'TECHNICIAN' | 'ADMIN';
    city?: string;
    neighborhood?: string;
    createdAt?: Date;
    updatedAt?: Date;
    active?: boolean;
    emailVerified?: boolean;
    phoneVerified?: boolean;
    profilePhotoUrl?: string;
    id?: { cause?: { stackTrace?: Array<{ classLoaderName?: string; moduleName?: string; moduleVersion?: string; methodName?: string; fileName?: string; lineNumber?: number; className?: string; nativeMethod?: boolean }>; message?: string; suppressed?: Array<{ stackTrace?: Array<{ classLoaderName?: string; moduleName?: string; moduleVersion?: string; methodName?: string; fileName?: string; lineNumber?: number; className?: string; nativeMethod?: boolean }>; message?: string; localizedMessage?: string }>; localizedMessage?: string }; stackTrace?: Array<{ classLoaderName?: string; moduleName?: string; moduleVersion?: string; methodName?: string; fileName?: string; lineNumber?: number; className?: string; nativeMethod?: boolean }>; message?: string; suppressed?: Array<{ stackTrace?: Array<{ classLoaderName?: string; moduleName?: string; moduleVersion?: string; methodName?: string; fileName?: string; lineNumber?: number; className?: string; nativeMethod?: boolean }>; message?: string; localizedMessage?: string }>; localizedMessage?: string };
    fullName?: string;
    client?: boolean;
    admin?: boolean;
    technician?: boolean;
}

export interface TechnicianDocumentDto {
    idDocument?: number;
    idProfile?: number;
    type?: 'IDENTITY_CARD' | 'CERTIFICATE' | 'DIPLOMA' | 'PHOTO' | 'INSURANCE';
    url?: string;
    uploadedAt?: Date;
    verified?: boolean;
    verificationNote?: string;
}

export interface RegisterDto {
    firstName: string;
    lastName: string;
    email: string;
    password: string;
    phone: string;
    city: string;
    neighborhood: string;
    profilePhotoUrl?: string;
}

export interface RegisterResponseDto {
    token?: string;
    userId?: number;
    firstName?: string;
    lastName?: string;
    email?: string;
    phone?: string;
    city?: string;
    neighborhood?: string;
    profilePhotoUrl?: string;
}

export interface AuthRequest {
    email?: string;
    password?: string;
}

export interface AuthResponse {
    token?: string;
    userId?: number;
    firstName?: string;
    lastName?: string;
    role?: 'CLIENT' | 'TECHNICIAN' | 'ADMIN';
    active?: boolean;
    profilePhotoUrl?: string;
}

export interface RegisterAdminDto {
    firstName?: string;
    lastName?: string;
    email?: string;
    password?: string;
    phone?: string;
    city?: string;
    neighborhood?: string;
    profilePhotoUrl?: string;
}

export interface TechnicianResultSearchDto {
    name?: string;
    verified?: boolean;
    averageRating?: number;
    availabilityStatus?: 'AVAILABLE' | 'BUSY' | 'UNAVAILABLE' | 'ON_BREAK';
    hourlyRate?: number;
    skillName?: string;
    yearsOfExperience?: number;
    city?: string;
    neighborhood?: string;
    profilePhotoUrl?: string;
}

export interface UserDto {
    idUser?: number;
    firstName?: string;
    lastName?: string;
    email?: string;
    phone?: string;
    role?: 'CLIENT' | 'TECHNICIAN' | 'ADMIN';
    city?: string;
    neighborhood?: string;
    active?: boolean;
    emailVerified?: boolean;
    phoneVerified?: boolean;
    profilePhotoUrl?: string;
    createdAt?: Date;
}

export interface ClientDto {
    firstName?: string;
    lastName?: string;
    email?: string;
    password?: string;
    phone?: string;
    city?: string;
    neighborhood?: string;
    profilePhotoUrl?: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
