/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for AuthController controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RegisterDto, RequestOptions, RegisterResponseDto, AuthRequest, AuthResponse } from "../models";

@Injectable({ providedIn: "root" })
export class AuthControllerService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;
    private readonly TOKEN_KEY = 'access_token';
    private readonly USER_KEY = 'auth_user';

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    register(registerDto: RegisterDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<RegisterResponseDto>;
    register(registerDto: RegisterDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RegisterResponseDto>>;
    register(registerDto: RegisterDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RegisterResponseDto>>;
    register(registerDto: RegisterDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/auth/register`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, registerDto, requestOptions);
    }

    logout(idUser: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    logout(idUser: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    logout(idUser: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    logout(idUser: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/auth/logout/${idUser}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, null, requestOptions);
    }

    login(authRequest: AuthRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<AuthResponse>;
    login(authRequest: AuthRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AuthResponse>>;
    login(authRequest: AuthRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AuthResponse>>;
    login(authRequest: AuthRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/auth/login`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, authRequest, requestOptions);
    }
}
