/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Avis controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, ReviewDto } from "../models";

@Injectable({ providedIn: "root" })
export class AvisService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getReviewById(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReviewDto>;
    getReviewById(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReviewDto>>;
    getReviewById(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReviewDto>>;
    getReviewById(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reviews/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    updateReview(id: number, reviewDto: ReviewDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReviewDto>;
    updateReview(id: number, reviewDto: ReviewDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReviewDto>>;
    updateReview(id: number, reviewDto: ReviewDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReviewDto>>;
    updateReview(id: number, reviewDto: ReviewDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reviews/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, reviewDto, requestOptions);
    }

    deleteReview(id: number, reason: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteReview(id: number, reason: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteReview(id: number, reason: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    deleteReview(id: number, reason: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reviews/${id}`;

        let params = new HttpParams();
        if (reason != null) {
            params = HttpParamsBuilder.addToHttpParams(params, reason, 'reason');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    createReview(reviewDto: ReviewDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReviewDto>;
    createReview(reviewDto: ReviewDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReviewDto>>;
    createReview(reviewDto: ReviewDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReviewDto>>;
    createReview(reviewDto: ReviewDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reviews`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, reviewDto, requestOptions);
    }

    countReviews(observe?: 'body', options?: RequestOptions<'blob'>): Observable<number>;
    countReviews(observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<number>>;
    countReviews(observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<number>>;
    countReviews(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reviews/stats/count`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getReviewForReservation(reservationId: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReviewDto>;
    getReviewForReservation(reservationId: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReviewDto>>;
    getReviewForReservation(reservationId: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReviewDto>>;
    getReviewForReservation(reservationId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reviews/reservation/${reservationId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getMyReviews(observe?: 'body', options?: RequestOptions<'blob'>): Observable<Array<ReviewDto>>;
    getMyReviews(observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<Array<ReviewDto>>>;
    getMyReviews(observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<Array<ReviewDto>>>;
    getMyReviews(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reviews/me`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getClientReviews(clientId: number, observe?: 'body', options?: RequestOptions<'blob'>): Observable<Array<ReviewDto>>;
    getClientReviews(clientId: number, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<Array<ReviewDto>>>;
    getClientReviews(clientId: number, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<Array<ReviewDto>>>;
    getClientReviews(clientId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reviews/client/${clientId}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
