/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for CategoryController controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, CategoryDto } from "../models";

@Injectable({ providedIn: "root" })
export class CategoryControllerService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getById1(id: number, observe?: 'body', options?: RequestOptions<'blob'>): Observable<CategoryDto>;
    getById1(id: number, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<CategoryDto>>;
    getById1(id: number, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<CategoryDto>>;
    getById1(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/categories/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'json',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    updateCategory(id: number, categoryDto: CategoryDto, observe?: 'body', options?: RequestOptions<'blob'>): Observable<CategoryDto>;
    updateCategory(id: number, categoryDto: CategoryDto, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<CategoryDto>>;
    updateCategory(id: number, categoryDto: CategoryDto, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<CategoryDto>>;
    updateCategory(id: number, categoryDto: CategoryDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/categories/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'json',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, categoryDto, requestOptions);
    }

    delete(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    delete(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    delete(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    delete(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/categories/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    getAllCategories(observe?: 'body', options?: RequestOptions<'blob'>): Observable<Array<CategoryDto>>;
    getAllCategories(observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<Array<CategoryDto>>>;
    getAllCategories(observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<Array<CategoryDto>>>;
    getAllCategories(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/categories`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'json',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    createCategory(categoryDto: CategoryDto, observe?: 'body', options?: RequestOptions<'blob'>): Observable<CategoryDto>;
    createCategory(categoryDto: CategoryDto, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<CategoryDto>>;
    createCategory(categoryDto: CategoryDto, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<CategoryDto>>;
    createCategory(categoryDto: CategoryDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/categories`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'json',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, categoryDto, requestOptions);
    }

    updateDisplayOrder(id: number, categoryDto: CategoryDto, observe?: 'body', options?: RequestOptions<'blob'>): Observable<CategoryDto>;
    updateDisplayOrder(id: number, categoryDto: CategoryDto, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<CategoryDto>>;
    updateDisplayOrder(id: number, categoryDto: CategoryDto, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<CategoryDto>>;
    updateDisplayOrder(id: number, categoryDto: CategoryDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/categories/${id}/order`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'json',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.patch(url, categoryDto, requestOptions);
    }

    updateIcon(id: number, categoryDto: CategoryDto, observe?: 'body', options?: RequestOptions<'blob'>): Observable<CategoryDto>;
    updateIcon(id: number, categoryDto: CategoryDto, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<CategoryDto>>;
    updateIcon(id: number, categoryDto: CategoryDto, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<CategoryDto>>;
    updateIcon(id: number, categoryDto: CategoryDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/categories/${id}/icon`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'json',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.patch(url, categoryDto, requestOptions);
    }

    deactivate(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deactivate(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deactivate(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    deactivate(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/categories/${id}/deactivate`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.patch(url, null, requestOptions);
    }

    activate(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    activate(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    activate(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    activate(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/categories/${id}/activate`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.patch(url, null, requestOptions);
    }

    countTechnicians(id: number, observe?: 'body', options?: RequestOptions<'blob'>): Observable<number>;
    countTechnicians(id: number, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<number>>;
    countTechnicians(id: number, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<number>>;
    countTechnicians(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/categories/${id}/technicians/count`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'json',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getActiveCategories(observe?: 'body', options?: RequestOptions<'blob'>): Observable<Array<CategoryDto>>;
    getActiveCategories(observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<Array<CategoryDto>>>;
    getActiveCategories(observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<Array<CategoryDto>>>;
    getActiveCategories(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/categories/active`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'json',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
