/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Clients controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, ReservationDto, ClientDto } from "../models";

@Injectable({ providedIn: "root" })
export class ClientsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    countActiveClients(observe?: 'body', options?: RequestOptions<'blob'>): Observable<number>;
    countActiveClients(observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<number>>;
    countActiveClients(observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<number>>;
    countActiveClients(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/clients/stats/count-active`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getMyReservations(observe?: 'body', options?: RequestOptions<'json'>): Observable<ReservationDto>;
    getMyReservations(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReservationDto>>;
    getMyReservations(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReservationDto>>;
    getMyReservations(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/clients/me/reservations`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getClientsByCity(city: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ClientDto>;
    getClientsByCity(city: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ClientDto>>;
    getClientsByCity(city: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ClientDto>>;
    getClientsByCity(city: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/clients/by-city`;

        let params = new HttpParams();
        if (city != null) {
            params = HttpParamsBuilder.addToHttpParams(params, city, 'city');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getActiveClients(observe?: 'body', options?: RequestOptions<'json'>): Observable<ClientDto>;
    getActiveClients(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ClientDto>>;
    getActiveClients(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ClientDto>>;
    getActiveClients(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/clients/active`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
