/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for CompétencesTechnicien controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { TechnicianSkillDto, RequestOptions } from "../models";

@Injectable({ providedIn: "root" })
export class CompétencesTechnicienService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    updateSkill(idSkill: number, technicianSkillDto: TechnicianSkillDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<TechnicianSkillDto>;
    updateSkill(idSkill: number, technicianSkillDto: TechnicianSkillDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TechnicianSkillDto>>;
    updateSkill(idSkill: number, technicianSkillDto: TechnicianSkillDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TechnicianSkillDto>>;
    updateSkill(idSkill: number, technicianSkillDto: TechnicianSkillDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-skills/${idSkill}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, technicianSkillDto, requestOptions);
    }

    deleteSkill(idSkill: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteSkill(idSkill: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteSkill(idSkill: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    deleteSkill(idSkill: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-skills/${idSkill}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    addSkill(technicianSkillDto: TechnicianSkillDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<TechnicianSkillDto>;
    addSkill(technicianSkillDto: TechnicianSkillDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TechnicianSkillDto>>;
    addSkill(technicianSkillDto: TechnicianSkillDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TechnicianSkillDto>>;
    addSkill(technicianSkillDto: TechnicianSkillDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-skills`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, technicianSkillDto, requestOptions);
    }

    verifySkill(idSkill: number, verified: boolean, observe?: 'body', options?: RequestOptions<'json'>): Observable<TechnicianSkillDto>;
    verifySkill(idSkill: number, verified: boolean, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TechnicianSkillDto>>;
    verifySkill(idSkill: number, verified: boolean, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TechnicianSkillDto>>;
    verifySkill(idSkill: number, verified: boolean, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-skills/${idSkill}/verify`;

        let params = new HttpParams();
        if (verified != null) {
            params = HttpParamsBuilder.addToHttpParams(params, verified, 'verified');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, null, requestOptions);
    }

    getMySkills(observe?: 'body', options?: RequestOptions<'json'>): Observable<TechnicianSkillDto>;
    getMySkills(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TechnicianSkillDto>>;
    getMySkills(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TechnicianSkillDto>>;
    getMySkills(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-skills/me`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getSkillsByCategory(categoryId: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<TechnicianSkillDto>;
    getSkillsByCategory(categoryId: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TechnicianSkillDto>>;
    getSkillsByCategory(categoryId: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TechnicianSkillDto>>;
    getSkillsByCategory(categoryId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-skills/category/${categoryId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
