/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for DocumentsTechnicien controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { TechnicianDocumentDto, RequestOptions } from "../models";

@Injectable({ providedIn: "root" })
export class DocumentsTechnicienService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    addDocument(technicianDocumentDto: TechnicianDocumentDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<TechnicianDocumentDto>;
    addDocument(technicianDocumentDto: TechnicianDocumentDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TechnicianDocumentDto>>;
    addDocument(technicianDocumentDto: TechnicianDocumentDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TechnicianDocumentDto>>;
    addDocument(technicianDocumentDto: TechnicianDocumentDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-documents`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, technicianDocumentDto, requestOptions);
    }

    verifyDocument(id: number, note?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    verifyDocument(id: number, note?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    verifyDocument(id: number, note?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    verifyDocument(id: number, note?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-documents/${id}/verify`;

        let params = new HttpParams();
        if (note != null) {
            params = HttpParamsBuilder.addToHttpParams(params, note, 'note');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, null, requestOptions);
    }

    rejectDocument(id: number, note?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    rejectDocument(id: number, note?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    rejectDocument(id: number, note?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    rejectDocument(id: number, note?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-documents/${id}/reject`;

        let params = new HttpParams();
        if (note != null) {
            params = HttpParamsBuilder.addToHttpParams(params, note, 'note');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, null, requestOptions);
    }

    getById2(id: number, observe?: 'body', options?: RequestOptions<'blob'>): Observable<TechnicianDocumentDto>;
    getById2(id: number, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<TechnicianDocumentDto>>;
    getById2(id: number, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<TechnicianDocumentDto>>;
    getById2(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-documents/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    deleteDocument(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteDocument(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteDocument(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    deleteDocument(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-documents/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    getBySkill(skillId: number, observe?: 'body', options?: RequestOptions<'blob'>): Observable<Array<TechnicianDocumentDto>>;
    getBySkill(skillId: number, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<Array<TechnicianDocumentDto>>>;
    getBySkill(skillId: number, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<Array<TechnicianDocumentDto>>>;
    getBySkill(skillId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-documents/skill/${skillId}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'json',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
