/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Factures controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, FactureDto } from "../models";

@Injectable({ providedIn: "root" })
export class FacturesService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getFactureById(idFacture: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<FactureDto>;
    getFactureById(idFacture: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FactureDto>>;
    getFactureById(idFacture: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FactureDto>>;
    getFactureById(idFacture: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/factures/${idFacture}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    updateFacture(idFacture: number, factureDto: FactureDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<FactureDto>;
    updateFacture(idFacture: number, factureDto: FactureDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FactureDto>>;
    updateFacture(idFacture: number, factureDto: FactureDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FactureDto>>;
    updateFacture(idFacture: number, factureDto: FactureDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/factures/${idFacture}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, factureDto, requestOptions);
    }

    deleteFacture(idFacture: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteFacture(idFacture: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteFacture(idFacture: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    deleteFacture(idFacture: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/factures/${idFacture}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    getAllFactures(observe?: 'body', options?: RequestOptions<'json'>): Observable<FactureDto>;
    getAllFactures(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FactureDto>>;
    getAllFactures(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FactureDto>>;
    getAllFactures(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/factures`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    createFacture(factureDto: FactureDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<FactureDto>;
    createFacture(factureDto: FactureDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FactureDto>>;
    createFacture(factureDto: FactureDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FactureDto>>;
    createFacture(factureDto: FactureDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/factures`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, factureDto, requestOptions);
    }

    getFacturesByReservation(idReservation: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<FactureDto>;
    getFacturesByReservation(idReservation: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FactureDto>>;
    getFacturesByReservation(idReservation: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FactureDto>>;
    getFacturesByReservation(idReservation: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/factures/reservation/${idReservation}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
