/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated service exports
* Do not edit this file manually
*/
export { AdminUserControllerService } from "./adminUserController.service";
export { AdminUsersService } from "./adminUsers.service";
export { AuthControllerService } from "./authController.service";
export { AuthenticationService } from "./authentication.service";
export { AvisService } from "./avis.service";
export { CategoriesService } from "./categories.service";
export { CategoryControllerService } from "./categoryController.service";
export { ClientControllerService } from "./clientController.service";
export { ClientsService } from "./clients.service";
export { CompétencesTechnicienService } from "./compétencesTechnicien.service";
export { FacturesService } from "./factures.service";
export { ProfilsTechnicienService } from "./profilsTechnicien.service";
export { ReservationControllerService } from "./reservationController.service";
export { ReservationsService } from "./reservations.service";
export { ReviewControllerService } from "./reviewController.service";
export { TechnicianControllerService } from "./technicianController.service";
export { TechnicianProfileControllerService } from "./technicianProfileController.service";
export { TechnicianSkillControllerService } from "./technicianSkillController.service";
export { TechniciensService } from "./techniciens.service";
