/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Reservations controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, ReservationDto } from "../models";

@Injectable({ providedIn: "root" })
export class ReservationsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getById(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReservationDto>;
    getById(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReservationDto>>;
    getById(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReservationDto>>;
    getById(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reservations/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    updateReservation(id: number, reservationDto: ReservationDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReservationDto>;
    updateReservation(id: number, reservationDto: ReservationDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReservationDto>>;
    updateReservation(id: number, reservationDto: ReservationDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReservationDto>>;
    updateReservation(id: number, reservationDto: ReservationDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reservations/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, reservationDto, requestOptions);
    }

    deleteReservation(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteReservation(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteReservation(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    deleteReservation(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reservations/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    createReservation(reservationDto: ReservationDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReservationDto>;
    createReservation(reservationDto: ReservationDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReservationDto>>;
    createReservation(reservationDto: ReservationDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReservationDto>>;
    createReservation(reservationDto: ReservationDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reservations`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, reservationDto, requestOptions);
    }

    changeStatus(id: number, status: 'PENDING' | 'ACCEPTED' | 'EN_ROUTE' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED' | 'REJECTED', observe?: 'body', options?: RequestOptions<'json'>): Observable<ReservationDto>;
    changeStatus(id: number, status: 'PENDING' | 'ACCEPTED' | 'EN_ROUTE' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED' | 'REJECTED', observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReservationDto>>;
    changeStatus(id: number, status: 'PENDING' | 'ACCEPTED' | 'EN_ROUTE' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED' | 'REJECTED', observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReservationDto>>;
    changeStatus(id: number, status: 'PENDING' | 'ACCEPTED' | 'EN_ROUTE' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED' | 'REJECTED', observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reservations/${id}/status`;

        let params = new HttpParams();
        if (status != null) {
            params = HttpParamsBuilder.addToHttpParams(params, status, 'status');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, null, requestOptions);
    }

    completeReservation(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReservationDto>;
    completeReservation(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReservationDto>>;
    completeReservation(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReservationDto>>;
    completeReservation(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reservations/${id}/complete`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, null, requestOptions);
    }

    cancelReservation(id: number, reason?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReservationDto>;
    cancelReservation(id: number, reason?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReservationDto>>;
    cancelReservation(id: number, reason?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReservationDto>>;
    cancelReservation(id: number, reason?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reservations/${id}/cancel`;

        let params = new HttpParams();
        if (reason != null) {
            params = HttpParamsBuilder.addToHttpParams(params, reason, 'reason');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, null, requestOptions);
    }

    getTechnicianRevenue(technicianId: number, observe?: 'body', options?: RequestOptions<'blob'>): Observable<number>;
    getTechnicianRevenue(technicianId: number, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<number>>;
    getTechnicianRevenue(technicianId: number, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<number>>;
    getTechnicianRevenue(technicianId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reservations/stats/revenue/${technicianId}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getTechnicianAverageRating(technicianId: number, observe?: 'body', options?: RequestOptions<'blob'>): Observable<number>;
    getTechnicianAverageRating(technicianId: number, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<number>>;
    getTechnicianAverageRating(technicianId: number, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<number>>;
    getTechnicianAverageRating(technicianId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reservations/stats/rating/${technicianId}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    countReservations(observe?: 'body', options?: RequestOptions<'blob'>): Observable<number>;
    countReservations(observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<number>>;
    countReservations(observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<number>>;
    countReservations(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reservations/stats/count`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    countPendingReservations(observe?: 'body', options?: RequestOptions<'blob'>): Observable<number>;
    countPendingReservations(observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<number>>;
    countPendingReservations(observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<number>>;
    countPendingReservations(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reservations/stats/count/pending`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    countAcceptedNow(observe?: 'body', options?: RequestOptions<'blob'>): Observable<number>;
    countAcceptedNow(observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<number>>;
    countAcceptedNow(observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<number>>;
    countAcceptedNow(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reservations/stats/count/accepted-now`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getMyTechnicianReservations(observe?: 'body', options?: RequestOptions<'blob'>): Observable<Array<ReservationDto>>;
    getMyTechnicianReservations(observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<Array<ReservationDto>>>;
    getMyTechnicianReservations(observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<Array<ReservationDto>>>;
    getMyTechnicianReservations(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reservations/me/technician`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getMyClientReservations(observe?: 'body', options?: RequestOptions<'blob'>): Observable<Array<ReservationDto>>;
    getMyClientReservations(observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<Array<ReservationDto>>>;
    getMyClientReservations(observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<Array<ReservationDto>>>;
    getMyClientReservations(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reservations/me/client`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    checkAvailability(technicianId: number, start: Date, end: Date, observe?: 'body', options?: RequestOptions<'blob'>): Observable<boolean>;
    checkAvailability(technicianId: number, start: Date, end: Date, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<boolean>>;
    checkAvailability(technicianId: number, start: Date, end: Date, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<boolean>>;
    checkAvailability(technicianId: number, start: Date, end: Date, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/reservations/availability`;

        let params = new HttpParams();
        if (technicianId != null) {
            params = HttpParamsBuilder.addToHttpParams(params, technicianId, 'technicianId');
        }
        if (start != null) {
            params = HttpParamsBuilder.addToHttpParams(params, start, 'start');
        }
        if (end != null) {
            params = HttpParamsBuilder.addToHttpParams(params, end, 'end');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
