/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Techniciens controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, Technician, TechnicianResultSearchDto } from "../models";

@Injectable({ providedIn: "root" })
export class TechniciensService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    validateKyc(technicianId: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    validateKyc(technicianId: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    validateKyc(technicianId: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    validateKyc(technicianId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technicians/${technicianId}/validate-kyc`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, null, requestOptions);
    }

    registerTechnician(technician: Technician, observe?: 'body', options?: RequestOptions<'json'>): Observable<Technician>;
    registerTechnician(technician: Technician, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Technician>>;
    registerTechnician(technician: Technician, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Technician>>;
    registerTechnician(technician: Technician, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technicians`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, technician, requestOptions);
    }

    getTechnicianById(technicianId: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Technician>;
    getTechnicianById(technicianId: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Technician>>;
    getTechnicianById(technicianId: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Technician>>;
    getTechnicianById(technicianId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technicians/${technicianId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    countActiveTechnicians(observe?: 'body', options?: RequestOptions<'blob'>): Observable<number>;
    countActiveTechnicians(observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<number>>;
    countActiveTechnicians(observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<number>>;
    countActiveTechnicians(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technicians/stats/active/count`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    searchTechnicians(city?: string, neighborhood?: string, categoryName?: string, availabilityStatus?: 'AVAILABLE' | 'BUSY' | 'UNAVAILABLE' | 'ON_BREAK', minRating?: number, minPrice?: number, maxPrice?: number, observe?: 'body', options?: RequestOptions<'blob'>): Observable<Array<TechnicianResultSearchDto>>;
    searchTechnicians(city?: string, neighborhood?: string, categoryName?: string, availabilityStatus?: 'AVAILABLE' | 'BUSY' | 'UNAVAILABLE' | 'ON_BREAK', minRating?: number, minPrice?: number, maxPrice?: number, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<Array<TechnicianResultSearchDto>>>;
    searchTechnicians(city?: string, neighborhood?: string, categoryName?: string, availabilityStatus?: 'AVAILABLE' | 'BUSY' | 'UNAVAILABLE' | 'ON_BREAK', minRating?: number, minPrice?: number, maxPrice?: number, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<Array<TechnicianResultSearchDto>>>;
    searchTechnicians(city?: string, neighborhood?: string, categoryName?: string, availabilityStatus?: 'AVAILABLE' | 'BUSY' | 'UNAVAILABLE' | 'ON_BREAK', minRating?: number, minPrice?: number, maxPrice?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technicians/search`;

        let params = new HttpParams();
        if (city != null) {
            params = HttpParamsBuilder.addToHttpParams(params, city, 'city');
        }
        if (neighborhood != null) {
            params = HttpParamsBuilder.addToHttpParams(params, neighborhood, 'neighborhood');
        }
        if (categoryName != null) {
            params = HttpParamsBuilder.addToHttpParams(params, categoryName, 'categoryName');
        }
        if (availabilityStatus != null) {
            params = HttpParamsBuilder.addToHttpParams(params, availabilityStatus, 'availabilityStatus');
        }
        if (minRating != null) {
            params = HttpParamsBuilder.addToHttpParams(params, minRating, 'minRating');
        }
        if (minPrice != null) {
            params = HttpParamsBuilder.addToHttpParams(params, minPrice, 'minPrice');
        }
        if (maxPrice != null) {
            params = HttpParamsBuilder.addToHttpParams(params, maxPrice, 'maxPrice');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getByNeighborhood(neighborhood: string, observe?: 'body', options?: RequestOptions<'blob'>): Observable<Array<Technician>>;
    getByNeighborhood(neighborhood: string, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<Array<Technician>>>;
    getByNeighborhood(neighborhood: string, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<Array<Technician>>>;
    getByNeighborhood(neighborhood: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technicians/search/neighborhood`;

        let params = new HttpParams();
        if (neighborhood != null) {
            params = HttpParamsBuilder.addToHttpParams(params, neighborhood, 'neighborhood');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getByCity(city: string, observe?: 'body', options?: RequestOptions<'blob'>): Observable<Array<Technician>>;
    getByCity(city: string, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<Array<Technician>>>;
    getByCity(city: string, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<Array<Technician>>>;
    getByCity(city: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technicians/search/city`;

        let params = new HttpParams();
        if (city != null) {
            params = HttpParamsBuilder.addToHttpParams(params, city, 'city');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getActiveTechnicians(observe?: 'body', options?: RequestOptions<'blob'>): Observable<Array<Technician>>;
    getActiveTechnicians(observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<Array<Technician>>>;
    getActiveTechnicians(observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<Array<Technician>>>;
    getActiveTechnicians(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technicians/active`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
