/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for TechnicianProfileController controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { TechnicianProfileCreateDto, RequestOptions, TechnicianProfileResponseDto, TechnicianProfileUpdateDto } from "../models";

@Injectable({ providedIn: "root" })
export class TechnicianProfileControllerService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    createProfile(technicianProfileCreateDto: TechnicianProfileCreateDto, observe?: 'body', options?: RequestOptions<'blob'>): Observable<TechnicianProfileResponseDto>;
    createProfile(technicianProfileCreateDto: TechnicianProfileCreateDto, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<TechnicianProfileResponseDto>>;
    createProfile(technicianProfileCreateDto: TechnicianProfileCreateDto, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<TechnicianProfileResponseDto>>;
    createProfile(technicianProfileCreateDto: TechnicianProfileCreateDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-profiles`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, technicianProfileCreateDto, requestOptions);
    }

    updateProfile(technicianProfileUpdateDto: TechnicianProfileUpdateDto, observe?: 'body', options?: RequestOptions<'blob'>): Observable<TechnicianProfileResponseDto>;
    updateProfile(technicianProfileUpdateDto: TechnicianProfileUpdateDto, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<TechnicianProfileResponseDto>>;
    updateProfile(technicianProfileUpdateDto: TechnicianProfileUpdateDto, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<TechnicianProfileResponseDto>>;
    updateProfile(technicianProfileUpdateDto: TechnicianProfileUpdateDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-profiles`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, technicianProfileUpdateDto, requestOptions);
    }

    validateProfile(technicianId: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    validateProfile(technicianId: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    validateProfile(technicianId: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    validateProfile(technicianId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-profiles/${technicianId}/validate`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, null, requestOptions);
    }

    updateAvailability(status: 'AVAILABLE' | 'BUSY' | 'UNAVAILABLE' | 'ON_BREAK', observe?: 'body', options?: RequestOptions<'blob'>): Observable<TechnicianProfileResponseDto>;
    updateAvailability(status: 'AVAILABLE' | 'BUSY' | 'UNAVAILABLE' | 'ON_BREAK', observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<TechnicianProfileResponseDto>>;
    updateAvailability(status: 'AVAILABLE' | 'BUSY' | 'UNAVAILABLE' | 'ON_BREAK', observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<TechnicianProfileResponseDto>>;
    updateAvailability(status: 'AVAILABLE' | 'BUSY' | 'UNAVAILABLE' | 'ON_BREAK', observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-profiles/availability`;

        let params = new HttpParams();
        if (status != null) {
            params = HttpParamsBuilder.addToHttpParams(params, status, 'status');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, null, requestOptions);
    }

    getProfile(technicianId: number, observe?: 'body', options?: RequestOptions<'blob'>): Observable<TechnicianProfileResponseDto>;
    getProfile(technicianId: number, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<TechnicianProfileResponseDto>>;
    getProfile(technicianId: number, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<TechnicianProfileResponseDto>>;
    getProfile(technicianId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-profiles/technician/${technicianId}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getPendingProfiles(observe?: 'body', options?: RequestOptions<'blob'>): Observable<Array<TechnicianProfileResponseDto>>;
    getPendingProfiles(observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<Array<TechnicianProfileResponseDto>>>;
    getPendingProfiles(observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<Array<TechnicianProfileResponseDto>>>;
    getPendingProfiles(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-profiles/pending`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getMyProfile(observe?: 'body', options?: RequestOptions<'blob'>): Observable<TechnicianProfileResponseDto>;
    getMyProfile(observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<TechnicianProfileResponseDto>>;
    getMyProfile(observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<TechnicianProfileResponseDto>>;
    getMyProfile(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/technician-profiles/me`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
